import Button from "../components/Button";
import { arrayInputsIdentity, arrayInputsAdress } from "../utils/Listing-inputs";
import Fieldset from "../components/Fieldset";
import Header from "../components/Header";
import Modal from "../components/Modal";
import { useState } from "react";
import { useDispatch } from "react-redux";
import { setData } from "../redux/employee";

const CreateEmployee = () => {
	const [showModal, setShowModal] = useState(false);
	const [formMessage, setFormMessage] = useState("");
	const myDispatch = useDispatch();

	const errorValidation = (arr) => {
		setFormMessage("Veuillez remplir tous les champs du formulaire !");
		arr.forEach((el) => (!el.value ? (el.className = "error-validation") : el.classList.remove("error-validation")));
	};

	const succesValidation = (arr) => {
		setFormMessage("");
		setShowModal(true);
		// const employee = {
		// 	firstName: arr[0].value,
		// 	lastName: arr[1].value,
		// 	begin: arr[3].value, // A SIMPLIFIER
		// 	department: arr[4].value,
		// 	birthday: arr[2].value,
		// 	street: arr[5].value,
		// 	city: arr[6].value,
		// 	state: arr[7].value,
		// 	zip: arr[8].value,
		// };

		// myDispatch(setData(employee));

		[
			{
				firstName: "Isabel",
				lastName: "Blanca",
				begin: "1973/03/20",
				department: "quis",
				birthday: "2000/10/13",
				street: "Portal Street",
				city: "Choctaw",
				state: "Missouri",
				zip: 50475,
			},
			{
				firstName: "Gladys",
				lastName: "Britney",
				begin: "1983/01/21",
				department: "dolor",
				birthday: "2015/05/08",
				street: "Blake Avenue",
				city: "Chicopee",
				state: "Mississippi",
				zip: 59196,
			},
			{
				firstName: "Hoover",
				lastName: "Hollie",
				begin: "2002/06/08",
				department: "sit",
				birthday: "2012/12/04",
				street: "Highland Boulevard",
				city: "Glenville",
				state: "Iowa",
				zip: 65784,
			},
			{
				firstName: "Pugh",
				lastName: "Carly",
				begin: "1972/04/18",
				department: "nisi",
				birthday: "1978/04/14",
				street: "Foster Avenue",
				city: "Blodgett",
				state: "Delaware",
				zip: 47455,
			},
			{
				firstName: "Anthony",
				lastName: "Regina",
				begin: "2004/01/11",
				department: "laborum",
				birthday: "1973/09/08",
				street: "Alton Place",
				city: "Edmund",
				state: "Oklahoma",
				zip: 73913,
			},
			{
				firstName: "Nichols",
				lastName: "Lawrence",
				begin: "2012/02/05",
				department: "duis",
				birthday: "1982/08/08",
				street: "Chauncey Street",
				city: "Waikele",
				state: "Hawaii",
				zip: 54262,
			},
			{
				firstName: "Trina",
				lastName: "Pope",
				begin: "1985/08/07",
				department: "sit",
				birthday: "1999/07/07",
				street: "Central Avenue",
				city: "Wheaton",
				state: "New York",
				zip: 51532,
			},
			{
				firstName: "Mai",
				lastName: "Kari",
				begin: "2009/05/26",
				department: "deserunt",
				birthday: "2016/11/05",
				street: "Scott Avenue",
				city: "Richford",
				state: "Guam",
				zip: 37462,
			},
			{
				firstName: "Marquez",
				lastName: "Harriet",
				begin: "2003/04/15",
				department: "incididunt",
				birthday: "1972/05/06",
				street: "Richmond Street",
				city: "Grayhawk",
				state: "Rhode Island",
				zip: 41896,
			},
			{
				firstName: "Moss",
				lastName: "Noemi",
				begin: "1999/12/06",
				department: "id",
				birthday: "1983/10/08",
				street: "Nostrand Avenue",
				city: "Bynum",
				state: "Northern Mariana Islands",
				zip: 75053,
			},
			{
				firstName: "French",
				lastName: "Gena",
				begin: "2004/06/16",
				department: "aliquip",
				birthday: "2013/01/31",
				street: "Moore Street",
				city: "Southmont",
				state: "Pennsylvania",
				zip: 60667,
			},
			{
				firstName: "Dodson",
				lastName: "Talley",
				begin: "1988/05/05",
				department: "reprehenderit",
				birthday: "1992/05/04",
				street: "Homecrest Avenue",
				city: "Clarktown",
				state: "Marshall Islands",
				zip: 28326,
			},
			{
				firstName: "Cline",
				lastName: "Thelma",
				begin: "1975/04/03",
				department: "adipisicing",
				birthday: "2004/03/14",
				street: "Doscher Street",
				city: "Falconaire",
				state: "Arizona",
				zip: 14328,
			},
			{
				firstName: "Stout",
				lastName: "Wong",
				begin: "1974/06/14",
				department: "cupidatat",
				birthday: "1990/06/26",
				street: "Grace Court",
				city: "Dola",
				state: "Wisconsin",
				zip: 51015,
			},
			{
				firstName: "Santiago",
				lastName: "Short",
				begin: "1992/12/02",
				department: "ex",
				birthday: "1987/02/19",
				street: "Gates Avenue",
				city: "Lowell",
				state: "Alabama",
				zip: 13697,
			},
			{
				firstName: "Coleman",
				lastName: "Mable",
				begin: "1984/05/10",
				department: "velit",
				birthday: "2019/01/29",
				street: "Thatford Avenue",
				city: "Mappsville",
				state: "Florida",
				zip: 62675,
			},
			{
				firstName: "Horn",
				lastName: "Alexander",
				begin: "2009/11/10",
				department: "esse",
				birthday: "2008/12/16",
				street: "Montague Terrace",
				city: "Neahkahnie",
				state: "Kansas",
				zip: 92587,
			},
			{
				firstName: "Gertrude",
				lastName: "Darla",
				begin: "1980/01/11",
				department: "quis",
				birthday: "1989/04/22",
				street: "Orient Avenue",
				city: "Bluffview",
				state: "Georgia",
				zip: 97065,
			},
			{
				firstName: "Morse",
				lastName: "Mayer",
				begin: "1981/06/02",
				department: "ad",
				birthday: "2015/07/28",
				street: "Fenimore Street",
				city: "Riceville",
				state: "Maine",
				zip: 61547,
			},
			{
				firstName: "Janell",
				lastName: "Woods",
				begin: "2012/12/10",
				department: "qui",
				birthday: "1998/01/15",
				street: "Downing Street",
				city: "Cannondale",
				state: "New Mexico",
				zip: 46379,
			},
			{
				firstName: "Terrie",
				lastName: "Luella",
				begin: "1970/07/07",
				department: "esse",
				birthday: "1985/08/03",
				street: "Provost Street",
				city: "Dubois",
				state: "Federated States Of Micronesia",
				zip: 89230,
			},
			{
				firstName: "Myra",
				lastName: "Katina",
				begin: "1981/12/26",
				department: "do",
				birthday: "2002/04/30",
				street: "Conway Street",
				city: "Flintville",
				state: "Connecticut",
				zip: 82893,
			},
			{
				firstName: "Valerie",
				lastName: "Gillespie",
				begin: "1989/01/17",
				department: "adipisicing",
				birthday: "2018/10/26",
				street: "Decatur Street",
				city: "Alafaya",
				state: "Massachusetts",
				zip: 46150,
			},
			{
				firstName: "Collier",
				lastName: "Duncan",
				begin: "1984/09/10",
				department: "quis",
				birthday: "2021/05/06",
				street: "Lawrence Street",
				city: "Mammoth",
				state: "Nevada",
				zip: 67320,
			},
			{
				firstName: "Vance",
				lastName: "Clements",
				begin: "1971/05/14",
				department: "deserunt",
				birthday: "1985/07/09",
				street: "Bond Street",
				city: "Hiwasse",
				state: "Michigan",
				zip: 69824,
			},
			{
				firstName: "Deidre",
				lastName: "Alta",
				begin: "2003/07/27",
				department: "veniam",
				birthday: "1971/01/21",
				street: "Irving Place",
				city: "Lafferty",
				state: "Minnesota",
				zip: 80156,
			},
			{
				firstName: "Foreman",
				lastName: "Wanda",
				begin: "2016/08/20",
				department: "veniam",
				birthday: "1993/01/15",
				street: "Vernon Avenue",
				city: "Morningside",
				state: "Montana",
				zip: 33166,
			},
			{
				firstName: "Ryan",
				lastName: "Hurst",
				begin: "2016/12/11",
				department: "tempor",
				birthday: "1986/12/09",
				street: "Johnson Street",
				city: "Bartley",
				state: "Puerto Rico",
				zip: 22285,
			},
			{
				firstName: "Bender",
				lastName: "Trisha",
				begin: "2007/11/12",
				department: "incididunt",
				birthday: "2005/06/28",
				street: "Harrison Place",
				city: "Islandia",
				state: "Vermont",
				zip: 15017,
			},
			{
				firstName: "Karina",
				lastName: "Norton",
				begin: "1995/04/13",
				department: "aute",
				birthday: "1989/11/20",
				street: "Porter Avenue",
				city: "Rockbridge",
				state: "Maryland",
				zip: 80897,
			},
			{
				firstName: "Marlene",
				lastName: "Sondra",
				begin: "1987/12/15",
				department: "fugiat",
				birthday: "2022/01/25",
				street: "Brooklyn Road",
				city: "Snowville",
				state: "Nebraska",
				zip: 36141,
			},
			{
				firstName: "Lindsay",
				lastName: "Jeanette",
				begin: "1989/07/12",
				department: "in",
				birthday: "2011/04/16",
				street: "Bragg Street",
				city: "Allamuchy",
				state: "Ohio",
				zip: 70013,
			},
			{
				firstName: "Pat",
				lastName: "Vega",
				begin: "2003/08/17",
				department: "sit",
				birthday: "1982/10/24",
				street: "Verona Street",
				city: "Fairfield",
				state: "Wyoming",
				zip: 47799,
			},
			{
				firstName: "Ericka",
				lastName: "Marsh",
				begin: "2016/12/16",
				department: "laboris",
				birthday: "1979/04/22",
				street: "Glen Street",
				city: "Devon",
				state: "Kentucky",
				zip: 68203,
			},
			{
				firstName: "Sallie",
				lastName: "Wilcox",
				begin: "1975/09/18",
				department: "qui",
				birthday: "2016/09/30",
				street: "Goodwin Place",
				city: "Fowlerville",
				state: "Virginia",
				zip: 71181,
			},
			{
				firstName: "Harrell",
				lastName: "Elaine",
				begin: "2021/01/30",
				department: "sint",
				birthday: "1980/10/09",
				street: "Throop Avenue",
				city: "Wollochet",
				state: "North Carolina",
				zip: 72052,
			},
			{
				firstName: "Carney",
				lastName: "Holt",
				begin: "1997/05/06",
				department: "veniam",
				birthday: "2020/04/14",
				street: "Aviation Road",
				city: "Wolcott",
				state: "North Dakota",
				zip: 21868,
			},
			{
				firstName: "Judith",
				lastName: "Holmes",
				begin: "2014/11/06",
				department: "id",
				birthday: "1992/04/17",
				street: "Ruby Street",
				city: "Vandiver",
				state: "Illinois",
				zip: 26847,
			},
			{
				firstName: "Juliet",
				lastName: "Monica",
				begin: "1999/11/07",
				department: "est",
				birthday: "1993/08/05",
				street: "Harway Avenue",
				city: "Floriston",
				state: "American Samoa",
				zip: 35434,
			},
			{
				firstName: "Dawson",
				lastName: "Lelia",
				begin: "1970/04/28",
				department: "ullamco",
				birthday: "1988/09/18",
				street: "Morton Street",
				city: "Delco",
				state: "Colorado",
				zip: 87650,
			},
			{
				firstName: "Carey",
				lastName: "Carol",
				begin: "2002/04/12",
				department: "cillum",
				birthday: "2021/12/06",
				street: "Holly Street",
				city: "Glasgow",
				state: "New Hampshire",
				zip: 84530,
			},
			{
				firstName: "Genevieve",
				lastName: "Dorothea",
				begin: "2011/04/21",
				department: "excepteur",
				birthday: "1997/06/20",
				street: "Alabama Avenue",
				city: "Mayfair",
				state: "Tennessee",
				zip: 81464,
			},
			{
				firstName: "Fitzgerald",
				lastName: "Brandie",
				begin: "2008/04/16",
				department: "et",
				birthday: "2002/04/28",
				street: "Chester Street",
				city: "Conway",
				state: "California",
				zip: 33926,
			},
			{
				firstName: "Bettie",
				lastName: "Dominguez",
				begin: "1996/05/07",
				department: "sit",
				birthday: "2012/09/29",
				street: "Crystal Street",
				city: "Riverton",
				state: "New Jersey",
				zip: 57433,
			},
			{
				firstName: "Harding",
				lastName: "Josefina",
				begin: "1988/02/20",
				department: "eiusmod",
				birthday: "1994/07/22",
				street: "Gerald Court",
				city: "Fairmount",
				state: "Arkansas",
				zip: 39692,
			},
			{
				firstName: "Marcella",
				lastName: "Kasey",
				begin: "1996/07/22",
				department: "id",
				birthday: "1992/01/13",
				street: "Ingraham Street",
				city: "Cherokee",
				state: "South Dakota",
				zip: 38370,
			},
			{
				firstName: "Cummings",
				lastName: "Leta",
				begin: "2008/03/13",
				department: "sunt",
				birthday: "1987/10/26",
				street: "Arkansas Drive",
				city: "Dupuyer",
				state: "Palau",
				zip: 98174,
			},
			{
				firstName: "Dorothy",
				lastName: "Bowman",
				begin: "1989/04/16",
				department: "exercitation",
				birthday: "2018/01/16",
				street: "Chester Avenue",
				city: "Delwood",
				state: "Virgin Islands",
				zip: 27743,
			},
			{
				firstName: "Georgina",
				lastName: "Cain",
				begin: "2022/01/19",
				department: "officia",
				birthday: "2009/08/04",
				street: "Lafayette Avenue",
				city: "Beason",
				state: "Louisiana",
				zip: 19672,
			},
			{
				firstName: "Velez",
				lastName: "Holman",
				begin: "1987/01/21",
				department: "laboris",
				birthday: "1979/08/28",
				street: "Story Street",
				city: "Ada",
				state: "Oregon",
				zip: 67973,
			},
			{
				firstName: "Reeves",
				lastName: "Johanna",
				begin: "1974/01/28",
				department: "est",
				birthday: "2014/11/03",
				street: "Banner Avenue",
				city: "Bainbridge",
				state: "Utah",
				zip: 77631,
			},
			{
				firstName: "Kirk",
				lastName: "Myrna",
				begin: "1995/09/17",
				department: "anim",
				birthday: "1981/10/28",
				street: "Lincoln Avenue",
				city: "Lloyd",
				state: "South Carolina",
				zip: 83490,
			},
			{
				firstName: "Jasmine",
				lastName: "Wilma",
				begin: "1984/01/26",
				department: "veniam",
				birthday: "1982/10/29",
				street: "Knapp Street",
				city: "Fairacres",
				state: "Indiana",
				zip: 26537,
			},
			{
				firstName: "Owens",
				lastName: "Jennings",
				begin: "1970/03/22",
				department: "pariatur",
				birthday: "2008/10/14",
				street: "Eckford Street",
				city: "Esmont",
				state: "Texas",
				zip: 45268,
			},
			{
				firstName: "Goff",
				lastName: "Abby",
				begin: "2003/07/02",
				department: "laborum",
				birthday: "1971/10/29",
				street: "Dunne Place",
				city: "Haena",
				state: "Alaska",
				zip: 28418,
			},
			{
				firstName: "Oliver",
				lastName: "Macdonald",
				begin: "1987/08/20",
				department: "fugiat",
				birthday: "2007/11/08",
				street: "Metropolitan Avenue",
				city: "Shepardsville",
				state: "Washington",
				zip: 60782,
			},
			{
				firstName: "Williams",
				lastName: "Robles",
				begin: "2008/08/30",
				department: "velit",
				birthday: "2019/11/20",
				street: "Meeker Avenue",
				city: "Caledonia",
				state: "District Of Columbia",
				zip: 15745,
			},
			{
				firstName: "Guerrero",
				lastName: "Little",
				begin: "1974/10/11",
				department: "proident",
				birthday: "2001/08/13",
				street: "Cass Place",
				city: "Disautel",
				state: "West Virginia",
				zip: 29446,
			},
			{
				firstName: "Kelly",
				lastName: "Sheri",
				begin: "2006/09/26",
				department: "deserunt",
				birthday: "1998/11/05",
				street: "Bay Parkway",
				city: "Kempton",
				state: "Missouri",
				zip: 95486,
			},
			{
				firstName: "Misty",
				lastName: "Paige",
				begin: "2017/05/26",
				department: "magna",
				birthday: "1971/04/19",
				street: "Desmond Court",
				city: "Bawcomville",
				state: "Mississippi",
				zip: 33069,
			},
			{
				firstName: "Sue",
				lastName: "Sellers",
				begin: "2008/01/24",
				department: "enim",
				birthday: "1976/05/05",
				street: "Powers Street",
				city: "Cartwright",
				state: "Iowa",
				zip: 55882,
			},
			{
				firstName: "Wilder",
				lastName: "Eugenia",
				begin: "2002/02/01",
				department: "cupidatat",
				birthday: "1992/05/24",
				street: "Dinsmore Place",
				city: "Lopezo",
				state: "Delaware",
				zip: 46466,
			},
			{
				firstName: "Norman",
				lastName: "Mandy",
				begin: "2019/04/16",
				department: "Lorem",
				birthday: "2006/04/02",
				street: "Berkeley Place",
				city: "Cucumber",
				state: "Oklahoma",
				zip: 52571,
			},
			{
				firstName: "Bryant",
				lastName: "Faye",
				begin: "2011/06/11",
				department: "magna",
				birthday: "1973/03/29",
				street: "Belmont Avenue",
				city: "Blairstown",
				state: "Hawaii",
				zip: 62139,
			},
			{
				firstName: "Rutledge",
				lastName: "Randolph",
				begin: "2014/05/22",
				department: "adipisicing",
				birthday: "1989/02/16",
				street: "Saratoga Avenue",
				city: "Freetown",
				state: "New York",
				zip: 93919,
			},
			{
				firstName: "Berta",
				lastName: "Antonia",
				begin: "1970/08/22",
				department: "consequat",
				birthday: "2020/08/10",
				street: "Evans Street",
				city: "Goochland",
				state: "Guam",
				zip: 33372,
			},
			{
				firstName: "Boyle",
				lastName: "Sandoval",
				begin: "1970/06/08",
				department: "amet",
				birthday: "1982/07/19",
				street: "Lynch Street",
				city: "Chapin",
				state: "Rhode Island",
				zip: 12624,
			},
			{
				firstName: "Best",
				lastName: "Moran",
				begin: "1972/02/25",
				department: "enim",
				birthday: "2011/11/24",
				street: "Celeste Court",
				city: "Ventress",
				state: "Northern Mariana Islands",
				zip: 77848,
			},
			{
				firstName: "Delacruz",
				lastName: "Latonya",
				begin: "2017/05/03",
				department: "ea",
				birthday: "2016/11/21",
				street: "Taylor Street",
				city: "Olney",
				state: "Pennsylvania",
				zip: 55422,
			},
			{
				firstName: "Leanne",
				lastName: "Mcintyre",
				begin: "1979/07/01",
				department: "occaecat",
				birthday: "1982/11/28",
				street: "Poplar Street",
				city: "Sunnyside",
				state: "Marshall Islands",
				zip: 69947,
			},
			{
				firstName: "Dianne",
				lastName: "Hillary",
				begin: "2014/03/06",
				department: "esse",
				birthday: "1971/02/22",
				street: "Elizabeth Place",
				city: "Charco",
				state: "Arizona",
				zip: 85835,
			},
			{
				firstName: "Angie",
				lastName: "Ebony",
				begin: "1972/09/01",
				department: "incididunt",
				birthday: "2017/03/13",
				street: "Brooklyn Avenue",
				city: "Imperial",
				state: "Wisconsin",
				zip: 23241,
			},
			{
				firstName: "Jamie",
				lastName: "Etta",
				begin: "1996/04/19",
				department: "occaecat",
				birthday: "2019/07/07",
				street: "Harbor Court",
				city: "Sandston",
				state: "Alabama",
				zip: 29964,
			},
			{
				firstName: "Minnie",
				lastName: "Gardner",
				begin: "1977/02/01",
				department: "consequat",
				birthday: "2007/04/23",
				street: "Burnett Street",
				city: "Wakulla",
				state: "Florida",
				zip: 43212,
			},
			{
				firstName: "Mcclain",
				lastName: "Lori",
				begin: "1980/10/26",
				department: "officia",
				birthday: "1981/03/08",
				street: "Dooley Street",
				city: "Davenport",
				state: "Kansas",
				zip: 50601,
			},
			{
				firstName: "Vonda",
				lastName: "Kelli",
				begin: "1997/02/20",
				department: "elit",
				birthday: "1995/11/16",
				street: "Tillary Street",
				city: "Wright",
				state: "Georgia",
				zip: 61796,
			},
			{
				firstName: "Latoya",
				lastName: "Nettie",
				begin: "1977/08/16",
				department: "Lorem",
				birthday: "1980/01/08",
				street: "Douglass Street",
				city: "Brandywine",
				state: "Maine",
				zip: 88167,
			},
			{
				firstName: "Miriam",
				lastName: "Abigail",
				begin: "2019/10/28",
				department: "esse",
				birthday: "2008/09/20",
				street: "Bergen Court",
				city: "Tilleda",
				state: "New Mexico",
				zip: 49698,
			},
			{
				firstName: "Mattie",
				lastName: "Mejia",
				begin: "2021/09/26",
				department: "cillum",
				birthday: "1984/01/23",
				street: "Melrose Street",
				city: "Caron",
				state: "Federated States Of Micronesia",
				zip: 28992,
			},
			{
				firstName: "Cara",
				lastName: "Serrano",
				begin: "1974/06/13",
				department: "consequat",
				birthday: "2009/11/05",
				street: "Irving Street",
				city: "Bonanza",
				state: "Connecticut",
				zip: 31411,
			},
			{
				firstName: "Maribel",
				lastName: "Shepard",
				begin: "1975/01/06",
				department: "laboris",
				birthday: "2007/05/08",
				street: "Seigel Court",
				city: "Winfred",
				state: "Massachusetts",
				zip: 87861,
			},
			{
				firstName: "Goodman",
				lastName: "Maldonado",
				begin: "1976/08/12",
				department: "aute",
				birthday: "2020/03/22",
				street: "Menahan Street",
				city: "Deseret",
				state: "Nevada",
				zip: 91339,
			},
			{
				firstName: "Molly",
				lastName: "Bradford",
				begin: "2018/11/11",
				department: "exercitation",
				birthday: "2019/01/09",
				street: "Vanderbilt Street",
				city: "Smock",
				state: "Michigan",
				zip: 19752,
			},
			{
				firstName: "Marcy",
				lastName: "Holly",
				begin: "1995/07/11",
				department: "minim",
				birthday: "1990/06/10",
				street: "Suydam Street",
				city: "Cloverdale",
				state: "Minnesota",
				zip: 89595,
			},
			{
				firstName: "Marta",
				lastName: "Denise",
				begin: "1972/10/31",
				department: "cupidatat",
				birthday: "2005/06/24",
				street: "Ira Court",
				city: "Aberdeen",
				state: "Montana",
				zip: 46336,
			},
			{
				firstName: "Madelyn",
				lastName: "Angela",
				begin: "1972/09/30",
				department: "cillum",
				birthday: "1976/10/05",
				street: "Debevoise Avenue",
				city: "Echo",
				state: "Puerto Rico",
				zip: 99439,
			},
			{
				firstName: "Mullen",
				lastName: "Meredith",
				begin: "2002/09/11",
				department: "ex",
				birthday: "2015/09/27",
				street: "Oriental Court",
				city: "Ogema",
				state: "Vermont",
				zip: 75182,
			},
			{
				firstName: "Keri",
				lastName: "Selma",
				begin: "1980/04/23",
				department: "velit",
				birthday: "1996/10/01",
				street: "Midwood Street",
				city: "Balm",
				state: "Maryland",
				zip: 64769,
			},
			{
				firstName: "Sara",
				lastName: "Vera",
				begin: "2008/03/05",
				department: "magna",
				birthday: "1985/05/28",
				street: "Prescott Place",
				city: "Lydia",
				state: "Nebraska",
				zip: 80281,
			},
			{
				firstName: "Clarissa",
				lastName: "Chandra",
				begin: "1973/10/03",
				department: "veniam",
				birthday: "2017/03/02",
				street: "Amber Street",
				city: "Lindisfarne",
				state: "Ohio",
				zip: 82051,
			},
			{
				firstName: "Stephenson",
				lastName: "Ray",
				begin: "1989/03/29",
				department: "qui",
				birthday: "2019/07/05",
				street: "Fair Street",
				city: "Nicut",
				state: "Wyoming",
				zip: 78989,
			},
			{
				firstName: "Aida",
				lastName: "Tamra",
				begin: "2006/10/21",
				department: "est",
				birthday: "1988/09/28",
				street: "Plaza Street",
				city: "Moraida",
				state: "Kentucky",
				zip: 86939,
			},
			{
				firstName: "James",
				lastName: "Marylou",
				begin: "1993/01/09",
				department: "esse",
				birthday: "1993/10/17",
				street: "Hart Street",
				city: "Conestoga",
				state: "Virginia",
				zip: 54415,
			},
			{
				firstName: "Sims",
				lastName: "Mccoy",
				begin: "1975/06/15",
				department: "veniam",
				birthday: "1993/12/27",
				street: "Etna Street",
				city: "Blandburg",
				state: "North Carolina",
				zip: 19116,
			},
			{
				firstName: "Sheila",
				lastName: "Ochoa",
				begin: "2020/06/12",
				department: "adipisicing",
				birthday: "2019/07/01",
				street: "Lewis Avenue",
				city: "Oretta",
				state: "North Dakota",
				zip: 17726,
			},
			{
				firstName: "May",
				lastName: "Bonita",
				begin: "2016/12/02",
				department: "aliquip",
				birthday: "1984/08/19",
				street: "Devon Avenue",
				city: "Trail",
				state: "Illinois",
				zip: 79995,
			},
			{
				firstName: "Bruce",
				lastName: "Bertha",
				begin: "2008/03/22",
				department: "Lorem",
				birthday: "2000/05/05",
				street: "Milford Street",
				city: "Jenkinsville",
				state: "American Samoa",
				zip: 75325,
			},
			{
				firstName: "Leola",
				lastName: "Cannon",
				begin: "2012/03/19",
				department: "labore",
				birthday: "2008/04/17",
				street: "Lefferts Place",
				city: "Grandview",
				state: "Colorado",
				zip: 80360,
			},
			{
				firstName: "Hendrix",
				lastName: "Palmer",
				begin: "2019/07/24",
				department: "voluptate",
				birthday: "2010/09/03",
				street: "Clarkson Avenue",
				city: "Shasta",
				state: "New Hampshire",
				zip: 76501,
			},
			{
				firstName: "Woodard",
				lastName: "Naomi",
				begin: "1986/11/25",
				department: "incididunt",
				birthday: "2011/07/28",
				street: "Sumpter Street",
				city: "Fairhaven",
				state: "Tennessee",
				zip: 88068,
			},
			{
				firstName: "Vivian",
				lastName: "Shawn",
				begin: "2002/12/05",
				department: "nulla",
				birthday: "2014/01/02",
				street: "Strong Place",
				city: "Dixonville",
				state: "California",
				zip: 81860,
			},
			{
				firstName: "Bridges",
				lastName: "Larson",
				begin: "2006/11/09",
				department: "do",
				birthday: "2002/05/11",
				street: "Cumberland Street",
				city: "Corriganville",
				state: "New Jersey",
				zip: 78035,
			},
		].forEach((el) => myDispatch(setData(el)));
	};

	const sendData = (e) => {
		e.preventDefault();
		const inputs = [...document.querySelectorAll("input")];
		inputs.splice(4, 0, document.querySelector("select"));
		succesValidation(inputs);
	};
	return (
		<>
			<Header />
			<section className="container">
				<form id="create-employee" onSubmit={(e) => sendData(e)}>
					<Fieldset wrapperClass={" fieldset employee"} legend={"Employee"} array={arrayInputsIdentity} />
					<Fieldset wrapperClass={"fieldset adress"} legend={"Adress"} array={arrayInputsAdress} />
					<Button nameClass="create-btn" text={"Create"} />
				</form>
				<p className="validator">{formMessage}</p>
				{showModal && <Modal wxc={setShowModal} />}
			</section>
		</>
	);
};

export default CreateEmployee;
